<?php

namespace {

    use SilverStripe\CMS\Model\SiteTree;

    class Page extends SiteTree
    {
        private static $db = [
            'Test' => 'Int'
        ];

        private static $has_one = [];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub

            $fields->addFieldsToTab('Root.Main', Marcz\SSCounter\SSCounterField::create('Test'));

            return $fields;
        }
    }
}
