<?php

namespace {

    use SilverStripe\CMS\Model\SiteTree;
    use Marcz\SSCounter\SSCounterField;

    class Page extends SiteTree
    {
        private static $db = [
            'Test' => 'Int'
        ];

        private static $has_one = [];

        public function getCMSFields()
        {
            $fields = parent::getCMSFields(); // TODO: Change the autogenerated stub

            $fields->addFieldToTab(
                'Root.Main',
                SSCounterField::create('Test', 'Test', 0)->addExtraClass('sscounter sscounter-info')
            );

            return $fields;
        }
    }
}
